{
 "title": "Doorman Observe",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Client Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "doorman_server_subclients{}" }
   ]
  },
  {
   "title": "Doorman server has",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "doorman_server_wants{}" }
   ]
  },
  {
   "title": "Doorman server wants",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "doorman_server_wants{}" }
   ]
  },
  {
   "title": "QPS per client",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(client_calls_total{}[1m])" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Doorman go-routine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"host.docker.internal:15050\"}"
    }
   ]
  },
  {
   "title": "Doorman Resource Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(doorman_server_requests{method=~\"GetCapacity|ReleaseCapacity\"}[1m])"
    }
   ]
  }
 ]
}