version: '3.7'

services:
  prometheus:
    build:
      context: .
      dockerfile: prom.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
  grafana:
    build:
      context: .
      dockerfile: grafana.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  prom_data: