global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'doorman_client'
    static_configs:
      - targets: ['host.docker.internal:8080','host.docker.internal:9090','host.docker.internal:15050']